alias info1='bash $HOME/Scripts/info.sh && fortune && echo '
alias removeduplicates="awk '!seen[$0]++'"
alias ls='ls --color=auto'
alias ll='ls -la'
alias l.='ls -d .* --color=auto'
alias bashit='source ~/.bashrc'
alias ..='cd ..'
alias ...='cd ../../../'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias update='sudo apt-get update && sudo apt-get upgrade'
alias reboot='sudo /sbin/reboot'
alias poweroff='sudo /sbin/poweroff'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
alias wget='wget -c'
alias rm='rm -i'
alias exip='wget http://ipecho.net/plain -O - -q ; echo'
alias cli='curl http://www.commandlinefu.com/commands/browse/sort-by-votes/plaintext'
alias starwars='telnet towel.blinkenlights.nl'
alias a='echo "------------Your aliases------------";alias'
alias m="bash $HOME/Scripts/call"
