#! /bin/sh

bspc config border_width        2
bspc config window_gap         35

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d 1 2 3 4 5
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor DFP10 -d I II III IV
#bspc monitor DFP11 -d V VI VII

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^1
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
$HOME/.config/polybar/launch.sh
compton &
